### ISSUE TITLE
To-do list

### ISSUE THREAD

**Issue by johndhancock** [DallasMorningNews/sportsday-top-recruits#1]
- [x] Dropdowns need to be styled and positioned
- [ ] Metadata and refers need to be written
- [x] Updated date needs to be scripted dynamically
- [x] Tables and content need to be styled for position popups 
- [ ] Dynamically loading data via ajax call needs to be included and noted for later use
- [x] Page needs to be made responsive
- [x] Need to update lat longs with matching data from SportsDay staff
